version: "3.8"

services:
  sleepcycle:
      container_name: sleepCycle
      build:
          context: .
          dockerfile: Dockerfile
      ports:
        - "8081:8081"
      depends_on:
        - database
      networks:
        - sleep_network

  database:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PasswordForWakeUpRenewed
      POSTGRES_DB: sleep_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sleep_network

volumes:
  postgres_data:

networks:
  sleep_network:
    driver: bridge
    name: sleep_network

