version: "3.8"

services:
  sleepcycle:
      container_name: sleepCycle
      build:
          context: .
          dockerfile: Dockerfile
      depends_on:
        database:
          condition: service_healthy
      ports:
        - "8081:8081"
      networks:
        - sleep_network
      entrypoint: ["sh", "-c"]
      command:
        - >
          bash -c "./gradlew clean test" &&
          java -jar app.jar
  database:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PasswordForWakeUpRenewed
      POSTGRES_DB: sleep_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sleep_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d sleep_database" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  sleep_network:
    driver: bridge
    name: sleep_network

